//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Tools.Tools.Text.LineFilter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LineFilter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LineFilter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Tools.Tools.Text.LineFilter.LineFilter", typeof(LineFilter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Filter.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case-insensitive.
        /// </summary>
        internal static string CaseSensitiveOff {
            get {
                return ResourceManager.GetString("CaseSensitiveOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case-sensitive.
        /// </summary>
        internal static string CaseSensitiveOn {
            get {
                return ResourceManager.GetString("CaseSensitiveOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ConfigurationTitle {
            get {
                return ResourceManager.GetString("ConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter lines from text by plain text, keywords, or regular expression.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to filter.
        /// </summary>
        internal static string InputTextLabel {
            get {
                return ResourceManager.GetString("InputTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression.
        /// </summary>
        internal static string InvalidRegexTitle {
            get {
                return ResourceManager.GetString("InvalidRegexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep matching lines.
        /// </summary>
        internal static string InvertMatchOff {
            get {
                return ResourceManager.GetString("InvertMatchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude matching lines.
        /// </summary>
        internal static string InvertMatchOn {
            get {
                return ResourceManager.GetString("InvertMatchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Filter.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords (any).
        /// </summary>
        internal static string ModeKeywords {
            get {
                return ResourceManager.GetString("ModeKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match mode.
        /// </summary>
        internal static string ModeLabel {
            get {
                return ResourceManager.GetString("ModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain text.
        /// </summary>
        internal static string ModePlainText {
            get {
                return ResourceManager.GetString("ModePlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression.
        /// </summary>
        internal static string ModeRegex {
            get {
                return ResourceManager.GetString("ModeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered lines.
        /// </summary>
        internal static string OutputTextLabel {
            get {
                return ResourceManager.GetString("OutputTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In &quot;Keywords&quot; mode, separate keywords with whitespace. A line is kept when it contains any keyword.
        /// </summary>
        internal static string PatternDescription {
            get {
                return ResourceManager.GetString("PatternDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        internal static string PatternLabel {
            get {
                return ResourceManager.GetString("PatternLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grep filter log lines regex keywords find search.
        /// </summary>
        internal static string SearchKeywords {
            get {
                return ResourceManager.GetString("SearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Filter.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched {0} of {1} lines.
        /// </summary>
        internal static string SummaryFormat {
            get {
                return ResourceManager.GetString("SummaryFormat", resourceCulture);
            }
        }
    }
}
